apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 10sigs1subjects
  name: perf-deployment
  namespace: demo
spec:
  replicas: 1000
  selector:
    matchLabels:
      app: 10sigs1subjects
  strategy: {}
  template:
    metadata:
      labels:
        app: 10sigs1subjects
    spec:
      containers:
      - name: 10sigs1subjects
        image: artifactstest.azurecr.io/10sigs1subjects:1
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 10sigs1subjects
  name: perf-deployment2
  namespace: demo
spec:
  replicas: 1000
  selector:
    matchLabels:
      app: 10sigs1subjects
  strategy: {}
  template:
    metadata:
      labels:
        app: 10sigs1subjects
    spec:
      containers:
      - name: 10sigs1subjects
        image: artifactstest.azurecr.io/10sigs1subjects:1
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 10sigs1subjects
  name: perf-deployment3
  namespace: demo
spec:
  replicas: 1000
  selector:
    matchLabels:
      app: 10sigs1subjects
  strategy: {}
  template:
    metadata:
      labels:
        app: 10sigs1subjects
    spec:
      containers:
      - name: 10sigs1subjects
        image: artifactstest.azurecr.io/10sigs1subjects:1
status: {}
