apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: gatekeeper-system
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8888'
spec:
  selector: 
    control-plane: audit-controller
    gatekeeper.sh/operation: audit
    gatekeeper.sh/system: "yes"
  ports:
    - port: 443
      targetPort: 8888 
