apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
      service.beta.kubernetes.io/azure-dns-label-name: anlanduaddonperfprometheus-controlcluster
spec:
  selector: 
    app: prometheus-server
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 9090 
