apiVersion: v1
kind: Pod
metadata:
  name: 1image2
  namespace: governed
spec:
  containers:
    - name: 1tag150sigs
      image: addonregistry.azurecr.io/1tag150sigs:latest
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
      resources:
        requests:
          memory: 1k
          cpu: 10m
        limits:
          memory: 1k
          cpu: 10m
